### ISSUE TITLE
code？

### ISSUE THREAD

**Issue by haunglimin123** [HuaqingHe/JOINED#1]
Why didn't I see the code？-_-

**Comment by HuaqingHe** [comment]
The code will be released soon.&nbsp;



---Original---
From: ***@***.***&gt;
Date: Sun, Mar 13, 2022 17:49 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [HuaqingHe/JOINED] code？ (Issue #1)




 
Why didn't I see the code？-_-
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by haunglimin123** [comment]
Thanks!

**Comment by haunglimin123** [comment]
Can you tell me how the normalized average value of gamma competition evaluation feedback is mapped to the normal value in your paper? thank you
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sun, Mar 13, 2022 05:58 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [HuaqingHe/JOINED] code？ (Issue #1)

&nbsp;



 The code will be released soon.&amp;nbsp; 
 
 
 
 ---Original--- 
 From: ***@***.***&amp;gt; 
 Date: Sun, Mar 13, 2022 17:49 PM 
 To: ***@***.***&amp;gt;; 
 Cc: ***@***.***&amp;gt;; 
 Subject: [HuaqingHe/JOINED] code？ (Issue #1) 
 
 
 
 
   
 Why didn't I see the code？-_- 
   
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android.  
 You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&amp;gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HuaqingHe** [comment]
I remember where I replied to this question before. Well, by calculating the ratio of the pixel distance to the score of my own results, I then converted the scores of others into pixel distance.

**Comment by HuaqingHe** [comment]
> Can you tell me how the normalized average value of gamma competition evaluation feedback is mapped to the normal value in your paper? thank you &nbsp; &nbsp; ------------------&nbsp;Original&nbsp;------------------ From: ***@***.***&gt;; Date: &nbsp;Sun, Mar 13, 2022 05:58 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;; ***@***.***&gt;; Subject: &nbsp;Re: [HuaqingHe/JOINED] code？ (Issue #1) &nbsp; The code will be released soon.&amp;nbsp;
> […](#)
> ---Original--- From: ***@***.***&amp;gt; Date: Sun, Mar 13, 2022 17:49 PM To: ***@***.***&amp;gt;; Cc: ***@***.***&amp;gt;; Subject: [HuaqingHe/JOINED] code？ (Issue #1) Why didn't I see the code？-_- — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

I remember where I replied to this question before. Well, by calculating the ratio of the pixel distance to the score of my own results, I then converted the scores of others into pixel distance.

**Comment by HuaqingHe** [comment]
By the way, since I plan to expand my work, the code for this article will be posted with the following article. Probably by the end of the year.

**Comment by haunglimin123** [comment]
大佬就是大佬！厉害厉害带带我
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, Oct 11, 2022 05:36 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [HuaqingHe/JOINED] code？ (Issue #1)

&nbsp;



 
By the way, since I plan to expand my work, the code for this article will be posted with the following articles. Probably by the end of the year.
